// Comentários às questões 117 a 163 do caderno do usuário (enunciados resumidos; comentários próprios).
// rel: "N" = norma de 2020 confirma; "A" = edição anterior, atenção; "D" = doutrina e prática.
// [número, origem, gabarito oficial, rel, resumo do item, comentário]
const aguaFria = [
  ["117", "TELEBRAS, 2026", "Certo", "A",
   "A vazão máxima provável de um trecho pode ser obtida pela soma ponderada dos aparelhos ligados a ele, com fatores de simultaneidade definidos em norma.",
   "É a lógica do método dos pesos (consumo máximo provável): somam-se os pesos das peças e aplica-se Q = 0,3·√ΣP, em L/s. Os pesos constavam da edição de 1998. A edição de 2020 não traz tabela de pesos: pede método reconhecido ou fundamentado, empírico ou probabilístico, justificado no projeto (6.14.1 e 6.14.2). Mesmo assim, o item foi dado como certo em 2026, sinal de que a banca continua aceitando o método dos pesos como referência."],
  ["118", "ARSAL, 2026", "Certo", "N",
   "A pressão estática máxima nos pontos de utilização tem limite em norma, e o projetista deve adotar redutores de pressão ou outra solução quando a geometria do edifício gerar pressões maiores.",
   "O limite é de 400 kPa (40 mca) de pressão estática nos pontos de utilização (6.9.4). Em edifícios altos, a saída usual é dividir a distribuição em zonas de pressão, com válvulas ou estações redutoras (6.9.7 a 6.9.15) ou com reservatórios intermediários."],
  ["119", "TRF 6, 2025", "Errado", "N",
   "O reservatório deveria atender, no mínimo, ao maior valor entre a reserva de incêndio e o consumo normal de 24 h.",
   "O mínimo é o consumo normal de 24 h, e o volume de incêndio é somado quando armazenado no mesmo reservatório (6.5.6.2). É soma, e não escolha do maior."],
  ["120", "TRT 10, 2025", "Certo", "N",
   "Reservatórios elevados de edifícios públicos são divididos em dois ou mais compartimentos, e o menor deve atender ao pico de consumo durante a manutenção.",
   "É a regra do item 6.5.6.5. A única exceção é a residência unifamiliar isolada; edifício público não escapa da exigência."],
  ["121", "CTI, 2024", "Certo", "D",
   "Tubos plásticos termoestáveis são os que não podem ser amolecidos e moldados por aquecimento.",
   "Classificação de materiais. Os termoplásticos (PVC, CPVC, PPR) amolecem com o calor e podem ser remoldados; os termoestáveis, também chamados termofixos, não. A norma não trata dessa classificação."],
  ["122", "CTI, 2024", "Certo", "D",
   "Em redes com tubulações de cobre, as junções podem ser feitas por soldagem capilar.",
   "A solda por capilaridade é a união típica de tubos e conexões de cobre. A NBR 5626:2020 remete às normas de produto e de aplicação de cada material (6.6.1 e 7.2.3) e cita, na bibliografia, a NBR 15345, de instalação de tubos de cobre."],
  ["123", "FNDE, 2024", "Certo", "N",
   "A pressão dinâmica no ponto de utilização não pode ser inferior a 10 kPa (1 mca), mesmo em bacias com caixa de descarga.",
   "Na edição de 2020, o mínimo de 10 kPa vale em qualquer caso (6.9.2). A edição de 1998 abria exceções para a caixa de descarga (5 kPa) e para a válvula de descarga (15 kPa), que deixaram de existir. É um dos pontos em que material antigo induz a erro."],
  ["124", "Polícia Científica AL, 2023", "Certo", "D",
   "Hidrômetros taquimétricos são indicados para maiores vazões; os volumétricos, para menores.",
   "Os taquimétricos, ou velocimétricos, medem pela velocidade do fluxo em uma turbina e cobrem faixas maiores de vazão. Os volumétricos medem por câmaras de volume conhecido, são mais sensíveis em baixas vazões e mais sujeitos a impurezas. Assunto de medição, fora da NBR 5626."],
  ["125", "TJ ES, 2023", "Errado", "A",
   "O chumbo não é mais permitido, mas a norma autorizaria reparar instalações existentes sem substituí-las.",
   "O entendimento vem da edição de 1998: o chumbo não deve ser usado, e os reparos em instalações existentes devem prever a substituição desse material. A edição de 2020 não lista materiais; aplica a regra geral de que nenhum componente pode alterar a potabilidade nem transmitir toxicidade à água (5.1 e 5.2), o que leva à mesma conclusão."],
  ["126", "TBG, 2023", "Errado", "D",
   "A exposição de tubos de PVC à luz solar poderia comprometer a resistência e torná-los inadequados para instalações de água fria.",
   "O gabarito indica que a banca considerou a afirmação exagerada: a radiação solar afeta sobretudo a aparência e a resistência ao impacto, e o tubo devidamente protegido continua adequado. Para a norma de 2020, o ponto relevante é outro: componentes plásticos expostos à radiação ultravioleta devem ser protegidos (Anexo B, B.2.1 e B.2.2). Gabarito discutível; vale guardar a posição da banca."],
  ["127", "TBG, 2023", "Certo", "N",
   "É recomendável usar caixa de descarga, em vez de válvula de descarga, para evitar o golpe de aríete.",
   "A válvula de descarga fecha rapidamente uma vazão alta e é a fonte clássica de golpe de aríete. A norma limita a sobrepressão a 200 kPa (6.9.6 e 6.17.1) e cita a válvula de descarga como exemplo de aparelho que gera transiente de pressão (6.10.4.1)."],
  ["128", "Petrobras, 2022", "Certo", "D",
   "A fórmula de Fair-Whipple-Hsiao é indicada para tubos de pequeno diâmetro, como os das instalações prediais de água fria.",
   "É a fórmula empírica tradicional para pequenos diâmetros. A norma de 2020 aceita equações empíricas adequadas ao material e ao diâmetro, mas aponta a equação universal como a mais indicada (6.14.4, nota)."],
  ["129", "Petrobras, 2022", "Errado", "D",
   "Na equação de Darcy-Weisbach, a perda de carga unitária seria proporcional ao cubo da velocidade média.",
   "A perda de carga unitária é J = f·V²/(2g·D): proporcional ao quadrado da velocidade e inversamente proporcional ao diâmetro."],
  ["130", "Petrobras, 2022", "Errado", "D",
   "O método do consumo máximo possível usaria como unidade o tubo de 20 mm (3/4\").",
   "No método do consumo máximo possível, ou das seções equivalentes, a unidade é o tubo de 15 mm (1/2\"). Os demais diâmetros são expressos em número de tubos de 1/2\" equivalentes."],
  ["131", "Petrobras, 2022", "Errado", "N",
   "O diâmetro dos sub-ramais seria obtido diretamente por consulta à norma da ABNT ou ao catálogo do fabricante.",
   "A NBR 5626:2020 não tabela diâmetros de sub-ramais e afirma que não há diâmetro nominal mínimo para eles. O diâmetro resulta do dimensionamento: vazão, velocidade, perda de carga disponível e pressão mínima do aparelho (6.14.3). Tabelas de diâmetro mínimo de sub-ramal vêm de edições antigas e da literatura."],
  ["132", "Petrobras, 2022", "Errado", "A",
   "No método do consumo máximo provável, a vazão seria o coeficiente de descarga dividido pela soma dos pesos das peças.",
   "A expressão do método dos pesos é Q = C·√ΣP, com C = 0,30 L/s: o coeficiente multiplica a raiz quadrada da soma dos pesos. A fórmula e os pesos são da edição de 1998; a de 2020 não os traz, mas o método continua sendo cobrado."],
  ["133", "TELEBRAS, 2022", "Certo", "D",
   "Em uma tabela de comprimentos equivalentes para PVC rígido, o valor 1,5 do joelho de 90° corresponde à perda de carga de 1,5 m de tubo de PVC de 25 mm.",
   "Comprimento equivalente é o comprimento de tubo reto, de mesmo diâmetro, que causa a mesma perda de carga da conexão. O conjunto de valores do enunciado corresponde ao diâmetro de 25 mm nas tabelas usuais. A norma de 2020 apenas exige equações pertinentes para as perdas de carga (6.14.4)."],
  ["134", "FUB, 2022", "Certo", "D",
   "Toda a tubulação de água fria da instalação predial deve ser dimensionada para funcionar como conduto forçado.",
   "A distribuição predial trabalha sob pressão, com seção cheia. Na norma de 2020, isso aparece na exigência de pressão dinâmica mínima de 5 kPa em qualquer ponto da rede (6.9.3). O escoamento livre fica restrito aos extravasores (6.5.9.4)."],
  ["135", "SECONT ES, 2022", "Errado", "D",
   "Dimensionar pelo máximo consumo provável evitaria a perda de vazão com todas as torneiras abertas ao mesmo tempo.",
   "O consumo máximo provável parte da hipótese de que nem todas as peças funcionam ao mesmo tempo. Para uso simultâneo de todas, o método adequado é o do consumo máximo possível."],
  ["136", "MPE CE, 2020", "Certo", "A",
   "A velocidade da água na tubulação de distribuição de água fria que passa pelo shaft vertical deve ser inferior a 2,5 m/s.",
   "O gabarito segue critério numérico anterior à edição de 2020. Na norma atual não há teto obrigatório: a velocidade é limitada por ruído (NBR 10152), golpe de aríete e cavitação, e o valor de 3 m/s aparece só em nota (6.8.1 a 6.8.5). Uma assertiva que atribuísse à NBR 5626:2020 um limite obrigatório de 2,5 m/s ou de 3 m/s não encontraria apoio no texto."],
  ["137", "SLU DF, 2019", "Certo", "A",
   "Recomenda-se que a tomada de água do sub-ramal de aparelhos sujeitos a retrossifonagem fique em ponto da coluna no mínimo 40 cm acima da borda de transbordamento do aparelho.",
   "Regra clássica de proteção contra retrossifonagem, vinda de edições anteriores da norma e da literatura. Na edição de 2020, a proteção se apoia na separação atmosférica, na proteção localizada em cada ponto e na ventilação das colunas (6.15.2.2 a 6.15.2.4). Os itens 6.15.2.5 a 6.15.2.9 não estavam na cópia consultada; por isso não foi possível confirmar se os 40 cm permanecem no texto atual."],
  ["138", "STM, 2011", "Certo", "D",
   "Em instalações de recalque, prevê-se uma tubulação de sucção para cada bomba, com diâmetro uniforme e nunca inferior ao do recalque.",
   "Boa prática de hidráulica: sucções independentes e com diâmetro igual ou maior que o do recalque reduzem perdas e o risco de cavitação. A norma de 2020 não fixa diâmetros, mas exige no mínimo duas bombas independentes, sucção sem vórtice nem entrada de ar e verificação do NPSH disponível (6.5.11.2, 6.5.11.5 e 6.5.11.7)."],
  ["139", "STM, 2011", "Certo", "N",
   "Havendo mudança na posição de alvenarias ou na estrutura durante a execução, admite-se alterar o traçado das redes, desde que isso não interfira nos cálculos aprovados.",
   "A norma de 2020 admite alterações durante a execução, desde que previamente aprovadas (7.1.2), e exige o registro em desenhos conforme construído (7.6)."],
  ["140", "MEC, 2011", "Errado", "D",
   "No método baseado na probabilidade de uso simultâneo, somar-se-iam as vazões em todos os trechos da rede.",
   "No método probabilístico (consumo máximo provável) somam-se os pesos, e a vazão sai da raiz quadrada dessa soma. Somar vazões é o procedimento do consumo máximo possível."],
  ["141", "TJ ES, 2011", "Certo", "D",
   "Em estabelecimentos com horários rígidos de uso da água, como os de ensino, os ramais são dimensionados pelo consumo simultâneo máximo possível.",
   "Escolas, quartéis, vestiários e indústrias concentram o uso em horários definidos, com muitas peças funcionando juntas. Nesses casos, admite-se o uso simultâneo de todas as peças."],
  ["142", "ECT, 2011", "Errado", "D",
   "No método do consumo máximo provável, a vazão no ramal independeria dos tipos de peças ligadas a ele.",
   "A vazão depende da soma dos pesos, e cada tipo de peça tem peso próprio."],
  ["143 a 145", "ANTAQ, 2009", "Certo, Certo e Errado", "D",
   "Três itens sobre a figura de um sistema hidropneumático, com componentes identificados por letras: A seria a tubulação de distribuição; B, o dreno; C, um vacuômetro.",
   "Dependem da figura do caderno. A saída lateral junto à base do tanque (A) é a distribuição, e a saída no fundo (B) é o dreno. O componente C é um dispositivo de comando ligado ao quadro elétrico da bomba, e não um vacuômetro: o tanque hidropneumático trabalha com pressão positiva, acompanhada por manômetro e pressostato. Na norma de 2020, esse tipo de instalação é um sistema de pressurização (6.5.11)."],
  ["146", "TRT 17, 2009", "Certo", "N",
   "A separação atmosférica em uma peça de utilização evita a contaminação da água por retrossifonagem, em caso de queda de pressão no abastecimento.",
   "Corresponde às definições de retrossifonagem e de separação atmosférica (3.55 e 3.56). A norma considera a separação atmosférica padronizada o recurso mais efetivo contra o refluxo (6.15.2.3)."],
  ["147", "TCE TO, 2009", "D (quatro itens certos)", "N",
   "Cinco definições para julgar: pressão de serviço, coluna de distribuição, peça de utilização, registro de fechamento e tubo ventilador.",
   "Só a definição do registro está errada: ele serve para interromper o fluxo, usado totalmente aberto ou totalmente fechado, e não para manter a vazão constante (3.52). Coluna de distribuição e tubo ventilador conferem com a edição de 2020 (3.11 e 3.68). Pressão de serviço e peça de utilização ficam no trecho de definições ausente da cópia consultada."],
  ["148", "UNIPAMPA, 2009", "Errado", "D",
   "A válvula globo controlaria a direção do escoamento, permitindo-o em um só sentido.",
   "Quem permite o escoamento em um único sentido é a válvula de retenção. A válvula globo (registro de pressão) regula a vazão."],
  ["149", "UNIPAMPA, 2009", "Errado", "N",
   "Válvulas de boia seriam usadas para controlar ou interromper a saída de água de reservatórios e caixas de descarga.",
   "A boia controla a entrada de água. Na norma de 2020, a torneira de boia controla a admissão e limita o nível máximo operacional do reservatório (3.66 e 6.5.8.1)."],
  ["150", "Prefeitura de Ipojuca, 2009", "Errado", "A",
   "Segundo a NBR 5626:1998, a reserva mínima é de 24 h de consumo, sem contar o incêndio; e o consumo de um edifício de apartamentos seria o número de apartamentos multiplicado pelo consumo diário por apartamento.",
   "A primeira parte reproduz a edição de 1998. O erro está no cálculo: o consumo diário é estimado pela população atendida multiplicada pelo consumo por pessoa. Na edição de 2020, o mínimo continua sendo 24 h, com a soma do volume de incêndio quando armazenado junto (6.5.6.2), e a estimativa de consumo considera tipologia do edifício e população atendida, entre outros fatores (6.5.4)."],
  ["151", "IBRAM DF, 2009", "Errado", "D",
   "O sistema indireto de distribuição sem bombeamento seria comum nos grandes edifícios.",
   "O indireto sem bombeamento serve a casas e prédios baixos, em que a pressão da rede alcança o reservatório superior. Grandes edifícios exigem reservatório inferior e recalque."],
  ["152", "IBRAM DF, 2009", "Errado", "D",
   "Com pressão insuficiente na rede pública e abastecimento descontínuo, usam-se reservatórios inferior e superior, sem necessidade de bombas.",
   "Se a pressão da rede não leva a água ao reservatório superior, o recalque é indispensável. A norma de 2020 exige no mínimo duas bombas independentes (6.5.11.2)."],
  ["153", "INMETRO, 2009", "Errado", "D",
   "Em prédios residenciais, a reserva de incêndio não poderia ser inferior a 40% do consumo diário.",
   "A NBR 5626 não fixa percentual. A reserva de incêndio é definida pelas normas e pela legislação de segurança contra incêndio; a norma de água apenas manda somá-la quando armazenada no mesmo reservatório (6.5.6.2). As estimativas da literatura clássica são bem menores, da ordem de 15% a 20% do consumo diário."],
  ["154", "INMETRO, 2009", "Certo", "A",
   "Atribuem-se coeficientes de ponderação às peças de utilização, empregados no cálculo das vazões e no dimensionamento das tubulações.",
   "São os pesos do método do consumo máximo provável. O item vale como descrição do método, mas a tabela de pesos é da edição de 1998 e não consta da edição de 2020 (6.14.2)."],
  ["155", "INMETRO, 2009", "Certo", "D",
   "O barrilete ramificado é solução mais econômica que o barrilete concentrado.",
   "O ramificado usa menos tubulação, com os registros distribuídos pela cobertura. O concentrado reúne os registros em um só local, o que facilita a operação, mas consome mais tubos e conexões."],
  ["156", "TRE AP, 2007", "C", "D",
   "Múltipla escolha sobre válvulas. Alternativa correta: a válvula de retenção permite o escoamento em um único sentido.",
   "As demais erram porque a válvula de gaveta trabalha totalmente aberta ou totalmente fechada; a globo serve para regular a vazão; a boia controla a entrada de água; e a redutora de pressão protege a rede e os aparelhos, e não a bomba contra cavitação."],
  ["157", "TSE, 2007", "B", "D",
   "Múltipla escolha sobre a ligação predial. Alternativa correta: ramais prediais podem ser executados em PEAD.",
   "O cavalete é a estrutura que abriga o hidrômetro, e não a peça de tomada na rede. Hidrômetro superdimensionado mede pior as pequenas vazões. O ramal predial e a medição seguem as regras da concessionária (3.50 e 6.5.1.1)."],
  ["158", "TSE, 2007", "D", "D",
   "Múltipla escolha sobre materiais. Alternativa correta: tubos de ferro fundido são admitidos com pintura externa anticorrosiva e revestimento interno.",
   "Cerâmica é material de esgoto; chumbo não é admitido; PVC flexível não é usado nessas instalações. A edição de 2020 não lista materiais: exige resistência à corrosão das superfícies em contato com a água (5.4), proteção externa de tubulações metálicas enterradas (6.19.4.1) e os cuidados do Anexo B."],
];

const aguaQuente = [
  ["159", "Prefeitura de São Cristóvão, 2023", "B (cobre)", "D",
   "Múltipla escolha: material recomendado para os ramais de água quente depois do registro de pressão do misturador do chuveiro.",
   "O trecho depois do misturador conduz água quente ou misturada, e o PVC comum não resiste à temperatura. A escolha específica do cobre vem de recomendação de prática construtiva adotada pela banca. A NBR 5626:2020 não indica material: exige componentes adequados à temperatura máxima de operação (5.5 e 6.10.1)."],
  ["160", "DP DF, 2022", "Certo", "D",
   "Tubos e conexões de policloreto de vinila clorado são recomendados para instalações de água quente.",
   "O CPVC é o PVC com maior teor de cloro, o que eleva a resistência à temperatura. Ao lado de cobre, PPR e PEX, é material usual de água quente."],
  ["161", "MEC, 2011", "Certo", "D",
   "Termossifão é um circuito fechado em que a água aquecida circula por convecção, pela diferença de densidade entre a água fria e a quente.",
   "É o princípio da circulação natural em aquecedores solares e em sistemas sem bomba. Não confunda com o sifão térmico da NBR 5626:2020, que tem a função oposta: dificultar a passagem de calor por convecção na alimentação de água fria do reservatório de água quente (3.57 e 6.13.3.1)."],
  ["162", "ANATEL, 2009", "Errado", "N",
   "Em regiões onde a água atinge temperaturas muito baixas, deveria ser prevista água quente em todos os pontos de utilização.",
   "Não existe essa obrigação. A água quente atende às necessidades dos usuários e aos usos pretendidos (6.10.1)."],
  ["163", "FUB, 2009", "Errado", "D",
   "Conexões e tubos de aço galvanizado não poderiam ser usados em instalações prediais de água quente.",
   "Para a banca, não há essa proibição. A norma de 2020 não veta materiais específicos: exige adequação à temperatura e resistência à corrosão (5.4, 5.5 e 6.10.1)."],
];

module.exports = { aguaFria, aguaQuente };
