// Questões no estilo certo/errado, com gabarito comentado (texto próprio).
// [enunciado, gabarito, comentário]
const questoes = [
  ["A NBR 5626:2020 aplica-se aos sistemas prediais de água fria e de água quente, potável ou não potável, desde que instalados em edifícios residenciais.",
   "E", "A norma abrange somente água potável e vale para qualquer tipo de edifício, residencial ou não (seção 1)."],
  ["A edição de 2020 da NBR 5626 passou a tratar também dos sistemas prediais de água quente, tendo cancelado e substituído a NBR 7198:1993.",
   "C", "Além da NBR 5626:1998, a edição de 2020 cancelou e substituiu a NBR 7198:1993 (prefácio)."],
  ["O diâmetro nominal (DN) corresponde ao diâmetro interno medido da tubulação e é o valor a ser utilizado nos cálculos de perda de carga.",
   "E", "O DN é um número de classificação; não é objeto de medição nem de uso em cálculo (3.20)."],
  ["No aquecimento central privado, o aquecedor remoto atende pontos de utilização pertencentes a mais de uma unidade.",
   "E", "Essa é a definição de aquecimento central coletivo. No central privado, os pontos pertencem a uma mesma unidade (3.7 e 3.8)."],
  ["O projeto dos sistemas prediais de água fria e água quente deve ser elaborado por profissional habilitado, cujos dados de registro devem constar dos elementos do projeto em qualquer etapa de seu desenvolvimento.",
   "C", "É o que estabelece o item 6.1.1."],
  ["Em edificação abastecida simultaneamente pela concessionária e por poço, admite-se a interligação das duas fontes sem dispositivo específico, desde que a água do poço atenda ao padrão de potabilidade.",
   "E", "Havendo uso simultâneo de outra fonte, deve existir meio de impedir o refluxo dessa água para a rede da concessionária (6.3.3)."],
  ["Quando o alimentador predial for instalado na mesma vala de tubulação enterrada potencialmente poluidora, sua geratriz inferior externa deve ficar em cota superior à da geratriz superior externa dessa tubulação.",
   "C", "O alimentador passa por cima da tubulação poluidora (6.5.3.2)."],
  ["O volume total de água reservado deve atender a, no mínimo, 24 h de consumo normal do edifício, devendo-se considerar o volume adicional de combate a incêndio quando armazenado conjuntamente.",
   "C", "Item 6.5.6.2."],
  ["Na impossibilidade de se determinar o volume máximo permissível de reservação, a norma exige que o volume total seja limitado a dois dias de consumo diário.",
   "E", "É recomendação, em nota, e o valor é de três dias de consumo diário, ou a previsão de meios que preservem as características da água (6.5.6.3)."],
  ["Todo reservatório elevado, inclusive o de residência unifamiliar isolada, deve ser dividido em dois ou mais compartimentos.",
   "E", "As residências unifamiliares isoladas são a exceção expressa (6.5.6.5)."],
  ["Em câmara formada pela interligação de vários reservatórios, é vedada a operação simultânea exclusiva como vasos comunicantes, devendo ser assegurada a circulação da água por todos eles.",
   "C", "Item 6.5.6.8."],
  ["As tubulações de extravasão e de limpeza de reservatórios de água potável podem ser interligadas diretamente ao sistema predial de águas pluviais, mas não ao de esgoto sanitário.",
   "E", "A interligação direta é vedada tanto com o esgoto sanitário quanto com as águas pluviais (6.5.9.10)."],
  ["As telas instaladas nas extremidades das tubulações de extravasão devem ter área de passagem das frestas superior à área da seção interna da respectiva tubulação.",
   "C", "Item 6.5.9.6."],
  ["A vazão de abastecimento do reservatório deve permitir a reposição do volume de consumo diário em até 6 h, prazo que cai para 3 h no caso de residências unifamiliares.",
   "C", "Item 6.7.2."],
  ["Os sistemas de recalque e de pressurização devem contar com, no mínimo, duas bombas de funcionamento independente, projetadas com alternância automática entre partidas consecutivas.",
   "C", "Itens 6.5.11.2 e 6.5.11.9."],
  ["O desvio (by-pass) do sistema de pressurização deve ser dotado de válvula de bloqueio, de modo que o abastecimento por gravidade só ocorra por acionamento manual.",
   "E", "O desvio tem válvula de retenção e não tem válvula de bloqueio, justamente para que o abastecimento por gravidade seja automático (6.5.11.18)."],
  ["Em qualquer caso, a pressão dinâmica da água no ponto de utilização não pode ser inferior a 5 kPa.",
   "E", "O mínimo no ponto de utilização é 10 kPa. Os 5 kPa valem para qualquer ponto da rede de distribuição (6.9.2 e 6.9.3)."],
  ["A pressão estática nos pontos de utilização não pode superar 400 kPa.",
   "C", "Item 6.9.4."],
  ["Sobrepressões decorrentes de transientes hidráulicos são admitidas, desde que não superem 200 kPa em relação à pressão dinâmica prevista em projeto.",
   "C", "Item 6.9.6."],
  ["A norma fixa, como requisito, a velocidade máxima de 3 m/s em qualquer trecho de tubulação, valor que elimina a ocorrência de golpe de aríete.",
   "E", "O valor aparece apenas em nota, e a própria nota esclarece que ele não evita o golpe de aríete, só limita os picos de sobrepressão (6.8.3)."],
  ["Estações redutoras de pressão que atendam a múltiplas unidades condominiais devem ser dotadas de pelo menos duas válvulas redutoras instaladas em série.",
   "E", "As válvulas são instaladas em paralelo, sendo uma sobressalente (6.9.7)."],
  ["Uma mesma estação redutora de pressão pode abastecer duas zonas de pressão, desde que respeitada a relação de redução de pressões das válvulas.",
   "E", "Cada estação redutora de pressão deve abastecer uma única zona de pressão (6.9.11)."],
  ["Onde houver possibilidade de a água quente ultrapassar 45 °C em pontos de utilização para uso corporal, deve-se empregar recurso de segurança intrínseca com atuação automática para limitar a temperatura a esse valor.",
   "C", "Item 6.10.4.3."],
  ["A tubulação de água fria que alimenta um aquecedor pode alimentar também válvula de descarga de bacia sanitária, desde que o aquecedor seja de acumulação.",
   "E", "Essa tubulação não pode alimentar aparelhos cuja operação cause transiente de pressão ou escaldamento, e a válvula de descarga é o exemplo citado (6.10.4.1)."],
  ["O sistema de distribuição de água quente deve ter isolamento térmico somente nos trechos com comprimento superior a 1,5 m.",
   "E", "O corpo da norma exige isolamento em toda a extensão (6.12.3). O valor de 1,5 m é recomendação de anexo informativo para sistemas sem recirculação (D.3.5)."],
  ["É vedada a instalação de qualquer válvula entre o recipiente de água quente e a válvula de alívio de pressão e temperatura.",
   "C", "Item 6.13.2.3."],
  ["Admite-se respiro coletivo para aquecedores de acumulação instalados em um mesmo pavimento.",
   "E", "O respiro coletivo é vedado (6.13.3.1)."],
  ["O trecho horizontal da tubulação de alimentação de água fria do reservatório de água quente deve receber isolamento térmico, para reduzir as perdas do sistema.",
   "E", "Esse trecho não pode ter isolamento térmico e deve ser de material resistente à água quente (6.13.1.5)."],
  ["A separação atmosférica padronizada é o recurso mais efetivo de prevenção ao refluxo, exigindo-se distância mínima de três vezes o diâmetro interno do tubo entre o ponto de suprimento e qualquer obstáculo periférico.",
   "C", "Item 6.15.2.3 e legenda das figuras de separação atmosférica (L ≥ 3d)."],
  ["Para um tubo de alimentação com diâmetro interno de 25 mm, a separação atmosférica mínima é de 25 mm.",
   "E", "Para diâmetros acima de 21 mm e até 41 mm, a separação mínima é de 70 mm (Tabela 1)."],
  ["Os quebradores de vácuo constituem proteção contra o refluxo inclusive nas situações em que este ocorre pelo mecanismo de vasos comunicantes.",
   "E", "A nota do item 6.15.2.3 afirma o contrário."],
  ["Duchas higiênicas e torneiras com gatilho de ponta devem ter válvulas de retenção, incorporadas ao aparelho ou instaladas no ponto de utilização.",
   "C", "Item 6.5.12.8."],
  ["No dimensionamento do sistema de distribuição, a vazão de cálculo de cada trecho deve ser obtida por método reconhecido ou devidamente fundamentado, que pode ser empírico ou probabilístico.",
   "C", "Item 6.14.2. O método adotado deve ser justificado no projeto (6.14.1)."],
  ["No ensaio de estanqueidade, cada seção da tubulação deve ser submetida a pressão mínima de 600 kPa ou de 1,5 vez a máxima pressão de trabalho, o que for maior.",
   "E", "Adota-se o menor dos dois valores (7.3.1.1)."],
  ["O ensaio de estanqueidade das tubulações de água quente deve ser feito com água a no mínimo 80 °C, após a aplicação do isolamento térmico.",
   "E", "A temperatura está correta, mas o ensaio é feito antes do isolamento térmico ou acústico e antes do recobrimento (7.3.1.3)."],
  ["O reservatório é considerado estanque se não forem detectados vazamentos ou extravasamentos durante um período mínimo de 72 h.",
   "C", "Item 7.3.3.3."],
  ["Conforme as periodicidades máximas da norma, a verificação do funcionamento das válvulas de alívio e das válvulas de segurança à pressão é semestral e cabe a profissional habilitado.",
   "C", "É a única atividade da Tabela 2 atribuída a profissional habilitado."],
  ["A limpeza dos reservatórios e do sistema de distribuição tem periodicidade máxima anual.",
   "E", "A periodicidade máxima é semestral (Tabela 2)."],
  ["No procedimento de desinfecção química descrito na norma, a concentração mínima de cloro livre no sistema é de 20 mg/L, mantendo-se o sistema em repouso por no mínimo 2 h.",
   "C", "Anexo F, itens F.3.3.2 e F.3.3.5."],
  ["Os anexos que tratam do ensaio de proteção contra refluxo e da proteção contra corrosão ou degradação são informativos.",
   "E", "Os Anexos A e B são normativos. Os informativos são C, D, E e F."],
];
module.exports = { questoes };
